// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function SelectDstRoot():Promise<string|Error>;

export function SelectImages():Promise<Array<string>|Error>;

export function Generate(arg1:main.Param):Promise<Error>;
