// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SelectDstRoot() {
  return window['go']['main']['App']['SelectDstRoot']();
}

export function SelectImages() {
  return window['go']['main']['App']['SelectImages']();
}

export function Generate(arg1) {
  return window['go']['main']['App']['Generate'](arg1);
}
